# Ode simulator configuration parameters
  /unicycle_dynamics_simulator/dt: 0.001      # Integration time step

  /unicycle_dynamics_simulator/x_0: 0.0      # Initial x position
  /unicycle_dynamics_simulator/y_0: 0.0      # Initial y position
  /unicycle_dynamics_simulator/theta_0: 0.0  # Initial theta position

